// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectionCreate(arg1) {
  return window['go']['main']['App']['ConnectionCreate'](arg1);
}

export function ConnectionDelete(arg1) {
  return window['go']['main']['App']['ConnectionDelete'](arg1);
}

export function ConnectionEdit(arg1) {
  return window['go']['main']['App']['ConnectionEdit'](arg1);
}

export function ConnectionList() {
  return window['go']['main']['App']['ConnectionList']();
}

export function DbList(arg1) {
  return window['go']['main']['App']['DbList'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
