// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectionCreate(arg1) {
  return window['go']['main']['App']['ConnectionCreate'](arg1);
}

export function ConnectionDelete(arg1) {
  return window['go']['main']['App']['ConnectionDelete'](arg1);
}

export function ConnectionEdit(arg1) {
  return window['go']['main']['App']['ConnectionEdit'](arg1);
}

export function ConnectionList() {
  return window['go']['main']['App']['ConnectionList']();
}

export function CreateKeyValue(arg1) {
  return window['go']['main']['App']['CreateKeyValue'](arg1);
}

export function DbInfo(arg1) {
  return window['go']['main']['App']['DbInfo'](arg1);
}

export function DbList(arg1) {
  return window['go']['main']['App']['DbList'](arg1);
}

export function DeleteKeyValue(arg1) {
  return window['go']['main']['App']['DeleteKeyValue'](arg1);
}

export function GetKeyValue(arg1) {
  return window['go']['main']['App']['GetKeyValue'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HashAddOrUpdateField(arg1) {
  return window['go']['main']['App']['HashAddOrUpdateField'](arg1);
}

export function HashFieldDelete(arg1) {
  return window['go']['main']['App']['HashFieldDelete'](arg1);
}

export function KeyList(arg1) {
  return window['go']['main']['App']['KeyList'](arg1);
}

export function ListValueCreate(arg1) {
  return window['go']['main']['App']['ListValueCreate'](arg1);
}

export function ListValueDelete(arg1) {
  return window['go']['main']['App']['ListValueDelete'](arg1);
}

export function SetValueCreate(arg1) {
  return window['go']['main']['App']['SetValueCreate'](arg1);
}

export function SetValueDelete(arg1) {
  return window['go']['main']['App']['SetValueDelete'](arg1);
}

export function UpdateKeyValue(arg1) {
  return window['go']['main']['App']['UpdateKeyValue'](arg1);
}

export function ZSetValueCreate(arg1) {
  return window['go']['main']['App']['ZSetValueCreate'](arg1);
}

export function ZSetValueDelete(arg1) {
  return window['go']['main']['App']['ZSetValueDelete'](arg1);
}
