// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';
import {main} from '../models';

export function ConnectionCreate(arg1:define.Connection):Promise<main.H>;

export function ConnectionDelete(arg1:string):Promise<main.H>;

export function ConnectionEdit(arg1:define.Connection):Promise<main.H>;

export function ConnectionList():Promise<main.H>;

export function Greet(arg1:string):Promise<string>;
